/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * New module of the cesium-webgpu render backend layer (not derived from any upstream file).
 *
 * **CPU-side uniform writer + per-frame uniform ring buffer** (tasks.md **T076**, FR-030; research
 * §5.4, data-model §4.3 `UniformRingBuffer` / `UniformBlockLayout`).
 *
 * The WebGPU backend has no `gl.uniform*` call: a uniform value reaches the GPU by writing bytes into
 * a `GPUBuffer` whose WGSL `struct` is generated by `bind-layout.ts`. This module is the CPU half of
 * that contract and it is **device-free** — it never touches a `GPUDevice`, which is exactly what
 * makes the write plan unit-testable under `node --test`.
 *
 * Invariants (data-model §4.3, research §5.4 H-4; G-4 is the input):
 *   - **every** byte offset comes from the layout table (`UniformField.byteOffset`, `arrayStride`,
 *     `columnStride`, `components`, `columns`, `length`, `scalar`). No stride is computed here, so the
 *     CPU bytes and the generated WGSL `struct` cannot drift apart silently;
 *   - a `paddedElement` member is a `vec4<T>` whose only meaningful lanes are the first `components`
 *     (bind-layout decision R-1): only those lanes are written, the padding is never touched;
 *   - `mat3`/`mat4` columns are 16-byte padded → `columnStride`;
 *   - GLSL `bool`/`bvec*` arrive as `u32`/`vecN<u32>` and accept `true`/`false`/`0`/`1`/numbers.
 *
 * **Missing values — decision (T076).** `tools/shader-verify.mjs` `serialiseScene()` pushes the name
 * of a struct member the fixed scene has no value for into `missingUniforms` and writes **no bytes**
 * for it; the `--variants=mvp` gate then asserts that list is empty (`shader-verify.mjs:437`). This
 * writer keeps precisely that semantic: a member without a value is skipped, writes nothing, and stays
 * observable (it never shows up in the returned plan; `UniformStaging.missingMembers` names it).
 * "No value" is a *normal* state — the union layout sizes `TEXTURE_UNITS` arrays for the largest
 * reachable variant — whereas writing `NaN`/garbage would be a silent corruption.
 * `DiagnosticError` (`category: "internal"`) is therefore reserved for the cases where skipping would
 * corrupt *neighbouring* state: a matrix/vector value shorter than its lane count, an array value
 * longer than the declared array (it would overwrite the next struct member), a value that cannot be
 * decoded as numbers, an unsupported scalar kind, or a write that does not fit the target buffer.
 *
 * Ported in spirit from the verified G-4 gate helper
 * (`experiments/gates/g4-uniform-layout/uniform-layout.mjs` `writeStructBytes()`), but driven by the
 * layout table alone and with the self-diff of the `createUniform` replacement layered on top.
 *
 * Zero dependencies, cross-platform, no `node:` import.
 */
import { DiagnosticError } from "./errors.js";
import { roundUp } from "./bind-layout.js";
import type { BindLayoutResult, UniformBlockLayout, UniformField } from "./bind-layout.js";
import type { DiagnosticErrorOptions } from "./errors.js";

// ------------------------------------------------------------------------------------------------
// diagnostics
// ------------------------------------------------------------------------------------------------

function internal(message: string, extra?: Readonly<Record<string, string | number | boolean>>): DiagnosticError {
  const options: DiagnosticErrorOptions = {
    backend: "webgpu",
    requirementRef: "FR-030",
    ...(extra === undefined ? {} : { extra }),
  };
  return new DiagnosticError("internal", `uniform-writer: ${message}`, options);
}

/** Human-readable shape of a rejected value (never its contents — uniform values may be user data). */
function describe(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean" || typeof value === "number") return `${typeof value} (${String(value)})`;
  if (Array.isArray(value)) return `an array of ${value.length}`;
  if (ArrayBuffer.isView(value)) return `a ${value.constructor.name} of length ${String((value as unknown as { length?: unknown }).length)}`;
  if (typeof value === "object") {
    const name = (value as { constructor?: { name?: unknown } }).constructor?.name;
    return typeof name === "string" && name.length > 0 ? `a ${name}` : "an object";
  }
  return typeof value;
}

// ------------------------------------------------------------------------------------------------
// scalar encoding
// ------------------------------------------------------------------------------------------------

/** The three scalar kinds a WGSL uniform member can hold (bind-layout maps GLSL `bool` → `u32`). */
export type UniformScalar = "f32" | "i32" | "u32";

/**
 * Encode one scalar for the uniform buffer.
 *
 * `f32` is rounded through `Math.fround` so the returned number is exactly what the buffer will hold
 * (and therefore what the self-diff of `createUniform` compares). `i32`/`u32` accept `true`/`false`
 * (the GLSL `bool` → `u32` mapping of bind-layout) as well as finite numbers; a non-finite number is
 * rejected instead of being silently truncated to `0`/`NaN`.
 */
export function encodeScalar(scalar: UniformScalar, value: unknown): number {
  if (scalar === "f32") {
    if (typeof value !== "number") throw internal(`an ${scalar} uniform value MUST be a number, received ${describe(value)}`);
    return Math.fround(value);
  }
  if (typeof value === "boolean") return value ? 1 : 0;
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw internal(`a ${scalar} uniform value MUST be a finite number, true or false, received ${describe(value)}`);
  }
  const truncated = Math.trunc(value);
  return scalar === "i32" ? truncated | 0 : truncated >>> 0;
}

/** Read back one scalar — little-endian, the byte order every WebGPU implementation uses. */
export function readScalar(view: DataView, byteOffset: number, scalar: UniformScalar): number {
  if (scalar === "f32") return view.getFloat32(byteOffset, true);
  return scalar === "i32" ? view.getInt32(byteOffset, true) : view.getUint32(byteOffset, true);
}

function writeScalar(view: DataView, byteOffset: number, scalar: UniformScalar, value: number): void {
  if (scalar === "f32") view.setFloat32(byteOffset, value, true);
  else if (scalar === "i32") view.setInt32(byteOffset, value, true);
  else view.setUint32(byteOffset, value, true);
}

// ------------------------------------------------------------------------------------------------
// value → lanes
// ------------------------------------------------------------------------------------------------

/** Anything addressable by index with a length: JS arrays, typed arrays, `Matrix2/3/4` (upstream). */
interface ArrayLikeValue {
  readonly length: number;
  readonly [index: number]: unknown;
}

function asArrayLike(value: unknown): ArrayLikeValue | null {
  if (typeof value !== "object" || value === null) return null;
  const length = (value as { readonly length?: unknown }).length;
  if (typeof length !== "number" || !Number.isSafeInteger(length) || length < 0) return null;
  return value as ArrayLikeValue;
}

/** `Color` exposes red/green/blue/alpha, the Cartesian types x/y/z/w — upstream accepts both. */
const COLOR_LANES: readonly string[] = ["red", "green", "blue", "alpha"];
const CARTESIAN_LANES: readonly string[] = ["x", "y", "z", "w"];

function namedLanes(value: object, expected: number, where: string): number[] {
  const record = value as Readonly<Record<string, unknown>>;
  const names = typeof record["red"] === "number" ? COLOR_LANES : CARTESIAN_LANES;
  const lanes: number[] = [];
  for (let index = 0; index < expected; index += 1) {
    const name = names[index];
    const lane = name === undefined ? undefined : record[name];
    if (typeof lane !== "number") {
      throw internal(`${where}: cannot read component ${index} — the value has no numeric "${String(name)}" (received ${describe(value)})`);
    }
    lanes.push(lane);
  }
  return lanes;
}

/**
 * The numeric lanes of one element value.
 *
 * A value that carries fewer lanes than the member declares is an error, never a silent zero fill:
 * in the terrain closure that can only mean a wrong uniform map entry, and a half-written matrix is
 * exactly the "silence would corrupt state" case of T076. `true`/`false` are accepted as `1`/`0`.
 */
function lanesOf(value: unknown, expected: number, where: string): number[] {
  if (typeof value === "number" || typeof value === "boolean") {
    if (expected !== 1) {
      throw internal(`${where}: ${expected} components are required, received the single ${describe(value)}`);
    }
    return [typeof value === "boolean" ? (value ? 1 : 0) : value];
  }
  const arrayLike = asArrayLike(value);
  if (arrayLike !== null) {
    if (arrayLike.length < expected) {
      throw internal(`${where}: ${expected} components are required, received ${arrayLike.length} (${describe(value)})`);
    }
    const lanes: number[] = [];
    for (let index = 0; index < expected; index += 1) {
      const lane = arrayLike[index];
      if (typeof lane === "number") lanes.push(lane);
      else if (typeof lane === "boolean") lanes.push(lane ? 1 : 0);
      else throw internal(`${where}: component ${index} is not a number (received ${describe(lane)})`);
    }
    return lanes;
  }
  if (typeof value === "object" && value !== null) return namedLanes(value, expected, where);
  throw internal(`${where}: cannot read ${expected} component(s) from ${describe(value)}`);
}

// ------------------------------------------------------------------------------------------------
// the write plan
// ------------------------------------------------------------------------------------------------

/** `data-model §4.3` write plan entry: one 4-byte scalar of the uniform struct. */
export interface UniformWritePlanEntry {
  readonly byteOffset: number;
  readonly scalar: UniformScalar;
  readonly value: number;
  readonly member: string;
  readonly element: number;
  readonly column: number;
  readonly component: number;
}

/** Scalars one *element* of a member occupies (a matrix element is `columns * components`). */
export function memberElementScalars(field: UniformField): number {
  return field.columns * field.components;
}

/**
 * Narrow the layout's `scalar` string to the encodable set.
 *
 * `UniformField.scalar` is a `string` in bind-layout (it is data, not a literal type), so the check
 * is real work: an unfamiliar scalar kind MUST stop the write instead of producing a struct the WGSL
 * side cannot read.
 */
function scalarKindOf(field: UniformField): UniformScalar {
  const scalar = field.scalar;
  if (scalar === "f32" || scalar === "i32" || scalar === "u32") return scalar;
  throw internal(`"${field.name}" declares the unsupported scalar kind "${scalar}" (expected f32, i32 or u32)`);
}

function pushElement(entries: UniformWritePlanEntry[], field: UniformField, element: number, value: unknown, where: string): void {
  const lanes = lanesOf(value, memberElementScalars(field), where);
  const scalar = scalarKindOf(field);
  const elementOffset = field.byteOffset + element * (field.arrayStride ?? 0);
  let lane = 0;
  for (let column = 0; column < field.columns; column += 1) {
    for (let component = 0; component < field.components; component += 1) {
      const raw = lanes[lane];
      lane += 1;
      if (raw === undefined) throw internal(`${where}: internal lane walk went out of bounds (layout/table mismatch)`);
      entries.push({
        byteOffset: elementOffset + column * (field.columnStride ?? 0) + component * 4,
        scalar,
        value: encodeScalar(scalar, raw),
        member: field.name,
        element,
        column,
        component,
      });
    }
  }
}

/**
 * The scalars one member value contributes, at the layout's own offsets.
 *
 * Returns an empty plan for an absent (`undefined`/`null`) value — see the module header for why that
 * is a recorded no-write and not an error. For an array member the value MUST be array-like: the
 * elements actually present are written, elements beyond the value are skipped, and a value **longer**
 * than the declared array throws (writing it would overwrite the next struct member).
 */
export function encodeMember(field: UniformField, value: unknown): readonly UniformWritePlanEntry[] {
  const entries: UniformWritePlanEntry[] = [];
  if (value === undefined || value === null) return entries;
  if (field.length > 1) {
    const arrayLike = asArrayLike(value);
    if (arrayLike === null) {
      throw internal(`"${field.name}" is ${field.wgslType}, so it needs an array of ${field.length} elements, received ${describe(value)}`);
    }
    if (arrayLike.length > field.length) {
      throw internal(`"${field.name}" received ${arrayLike.length} elements but the layout declares ${field.length}; the extra element(s) would overwrite "czm" struct members after it`);
    }
    for (let element = 0; element < arrayLike.length; element += 1) {
      const elementValue = arrayLike[element];
      if (elementValue === undefined || elementValue === null) continue;
      pushElement(entries, field, element, elementValue, `${field.name}[${element}]`);
    }
    return entries;
  }
  pushElement(entries, field, 0, value, field.name);
  return entries;
}

/**
 * Write a plan into the struct region `bytes` (which starts at the struct's byte 0).
 *
 * @returns the number of bytes written. Bounds are checked per scalar: a plan entry outside `bytes`
 *   raises `DiagnosticError` (`internal`) instead of silently dropping the value.
 */
export function applyPlan(entries: readonly UniformWritePlanEntry[], bytes: Uint8Array): number {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  for (const entry of entries) {
    if (entry.byteOffset < 0 || entry.byteOffset + 4 > bytes.byteLength) {
      throw internal(`scalar "${entry.member}" (element ${entry.element}, column ${entry.column}, component ${entry.component}) resolves to byte ${entry.byteOffset}, outside the ${bytes.byteLength}-byte struct region`);
    }
    writeScalar(view, entry.byteOffset, entry.scalar, entry.value);
  }
  return entries.length * 4;
}

// ------------------------------------------------------------------------------------------------
// writeStruct
// ------------------------------------------------------------------------------------------------

/**
 * The layout table and the WGSL struct MUST describe the same block (data-model §4.3).
 *
 * Only the *content* invariant is checked — `blockSize` is what the caller sizes the GPU buffer with.
 * The table identity (`members` vs `uniformBlock.fields`) is deliberately not asserted: a layout that
 * travelled through JSON (a gate fixture, an artefact) is legitimately a different array with the
 * same content.
 */
function assertConsistent(layout: BindLayoutResult): void {
  if (layout.uniformBlock.blockSize !== layout.structSize) {
    throw internal(`the layout is inconsistent: uniformBlock.blockSize=${layout.uniformBlock.blockSize} but structSize=${layout.structSize}`);
  }
}

export interface WriteStructOptions {
  /** Target buffer. Without it a fresh zero-filled `ArrayBuffer` of the struct size is allocated. */
  readonly into?: ArrayBuffer;
  /** Byte offset of the struct inside `into` (defaults to 0; the ring uses its slot offset). */
  readonly byteOffset?: number;
}

/**
 * Write every member of `values` that the layout declares, in the layout's own offsets.
 *
 * The padding bytes (`vec3` → 16, `mat3` columns, widened `vec4` array elements) are never touched;
 * with the default allocation they are therefore observable as zero.
 */
export function writeStruct(
  layout: BindLayoutResult,
  values: Readonly<Record<string, unknown>>,
  options: WriteStructOptions = {},
): { readonly bytes: Uint8Array; readonly plan: readonly UniformWritePlanEntry[]; readonly structSize: number } {
  assertConsistent(layout);
  const structSize = layout.structSize;
  const byteOffset = options.byteOffset ?? 0;
  if (!Number.isSafeInteger(byteOffset) || byteOffset < 0) {
    throw internal(`byteOffset MUST be a non-negative safe integer, received ${String(options.byteOffset)}`);
  }
  const target = options.into ?? new ArrayBuffer(Math.max(structSize, 16));
  if (byteOffset + structSize > target.byteLength) {
    throw internal(`the struct is ${structSize} bytes and does not fit ${target.byteLength} - ${byteOffset} = ${target.byteLength - byteOffset} available byte(s) at offset ${byteOffset}`);
  }
  const bytes = new Uint8Array(target, byteOffset, structSize);
  const plan: UniformWritePlanEntry[] = [];
  for (const member of layout.members) {
    const value = values[member.name];
    if (value === undefined || value === null) continue; // recorded no-write, see the module header
    for (const entry of encodeMember(member, value)) plan.push(entry);
  }
  applyPlan(plan, bytes);
  return { bytes, plan, structSize };
}

// ------------------------------------------------------------------------------------------------
// data-model §4.3 projection
// ------------------------------------------------------------------------------------------------

/** `data-model §4.3 UniformBlockLayout.fields[i]` — the field subset the pipeline code consumes. */
export interface UniformBlockFieldView {
  readonly name: string;
  readonly kind: string;
  readonly byteOffset: number;
  readonly byteSize: number;
  readonly arrayStride?: number;
}

/**
 * `UniformBlockLayout` (data-model §4.3) view of a layout, for the unit suite and the pipeline code.
 *
 * It is a *projection* of `BindLayoutResult.uniformBlock`, never a second source of truth: names,
 * order, offsets, sizes and the WGSL struct text are copied field for field.
 */
export function uniformBlockLayout(layout: BindLayoutResult): {
  readonly uniformNames: readonly string[];
  readonly fields: readonly UniformBlockFieldView[];
  readonly blockSize: number;
  readonly wgslStruct: string;
} {
  assertConsistent(layout);
  const block: UniformBlockLayout = layout.uniformBlock;
  return {
    uniformNames: [...block.uniformNames],
    fields: block.fields.map((field): UniformBlockFieldView => {
      const view: UniformBlockFieldView = {
        name: field.name,
        kind: field.kind,
        byteOffset: field.byteOffset,
        byteSize: field.byteSize,
        ...(field.arrayStride === null ? {} : { arrayStride: field.arrayStride }),
      };
      return view;
    }),
    blockSize: block.blockSize,
    wgslStruct: block.wgslStruct,
  };
}

// ------------------------------------------------------------------------------------------------
// ring buffer + staging
// ------------------------------------------------------------------------------------------------

/**
 * WebGPU requires every dynamic offset to be a multiple of
 * `GPULimits.minUniformBufferOffsetAlignment`, whose default (and floor) is 256.
 */
export const DEFAULT_DYNAMIC_OFFSET_ALIGNMENT = 256;

/** Command-level slots the default ring capacity reserves besides the automatic block. */
export const DEFAULT_COMMAND_SLOTS = 8;

/**
 * `data-model §4.3 UniformRingBuffer`: one `GPUBuffer`-backed `ArrayBuffer` per frame.
 *
 * `writeOffset` is the cursor of the current frame and `dynamicOffsetsUsed` records every offset
 * handed to `setBindGroup(..., dynamicOffsets)` so the pass encoder (and the evidence artefacts) can
 * report exactly how much of the ring a frame consumed.
 */
export interface UniformRingBuffer {
  readonly buffer: ArrayBuffer;
  readonly frameCapacityBytes: number;
  writeOffset: number;
  readonly dynamicOffsetsUsed: number[];
}

/**
 * Allocate the ring buffer of one frame.
 *
 * `frameCapacityBytes` MUST be a positive multiple of `alignment`: a ring whose capacity is not a
 * multiple would eventually hand out a dynamic offset that no device accepts, and rounding it
 * silently here would hide the sizing mistake from the caller that owns the frame budget.
 */
export function createRingBuffer(frameCapacityBytes: number, options: { readonly alignment?: number } = {}): UniformRingBuffer {
  const alignment = options.alignment ?? DEFAULT_DYNAMIC_OFFSET_ALIGNMENT;
  if (!Number.isSafeInteger(alignment) || alignment < 4 || (alignment & (alignment - 1)) !== 0) {
    throw internal(`the dynamic-offset alignment MUST be a power of two >= 4, received ${String(options.alignment)}`);
  }
  if (!Number.isSafeInteger(frameCapacityBytes) || frameCapacityBytes <= 0) {
    throw internal(`frameCapacityBytes MUST be a positive safe integer, received ${String(frameCapacityBytes)}`);
  }
  if (frameCapacityBytes % alignment !== 0) {
    throw internal(`frameCapacityBytes=${frameCapacityBytes} is not a multiple of the dynamic-offset alignment ${alignment}`);
  }
  return { buffer: new ArrayBuffer(frameCapacityBytes), frameCapacityBytes, writeOffset: 0, dynamicOffsetsUsed: [] };
}

/**
 * The sink a generated setter pushes changed values into.
 *
 * `createUniform`/`createUniformArray` diff their own values (upstream's lazy `set()`), so a sink is
 * only called when something really changed. `writeSampler` is optional because samplers are not
 * struct members: they live in the sampler bind group (data-model §4.3) and only a bind-group-capable
 * caller can serve them.
 */
export interface UniformWriteSink {
  /** One member of the program's uniform struct, already diffed by the caller. */
  writeMember(name: string, value: unknown): void;
  /** A sampler/texture pair; absent ⇒ the setter raises `not-implemented`. */
  writeSampler?(name: string, value: unknown): void;
}

/** Ring capacity that fits the automatic block plus `commandSlots` command-level slots. */
export function frameCapacityFor(layout: BindLayoutResult, alignment: number = DEFAULT_DYNAMIC_OFFSET_ALIGNMENT, commandSlots: number = DEFAULT_COMMAND_SLOTS): number {
  return roundUp(layout.structSize, alignment) * (1 + commandSlots);
}

/**
 * The per-frame uniform staging area of one shader program.
 *
 * Layout of the ring (all offsets are `alignment`-aligned by construction):
 *
 * ```
 *   [0, slotSize)                     automatic uniform block — written once per frame, lazily
 *   [slotSize, slotSize*(1+N))        command slots — one per draw command, addressed by dynamicOffset
 * ```
 *
 * `writeLazy` is the "automatic uniform block, once per frame" path (T076): it re-encodes the values
 * through the layout table and copies **only the scalars whose bytes actually differ**, so a frame
 * that changes nothing writes nothing. `writeCommand` is the `command.uniformMap` path: it always
 * takes a fresh slot and returns its dynamic offset. `beginFrame()` rewinds the command cursor.
 */
export class UniformStaging implements UniformWriteSink {
  readonly layout: BindLayoutResult;
  readonly alignment: number;
  /** Bytes one ring slot occupies: the struct size rounded up to the dynamic-offset alignment. */
  readonly slotSize: number;
  readonly ring: UniformRingBuffer;

  #bytesWritten = 0;
  #skippedWrites = 0;
  #missingMembers: readonly string[] = [];
  readonly #scratch: ArrayBuffer;

  constructor(layout: BindLayoutResult, options: { readonly frameCapacityBytes?: number; readonly alignment?: number } = {}) {
    assertConsistent(layout);
    if (layout.structSize <= 0) {
      throw internal(`struct "${layout.structName}" declares no numeric uniform member — there is nothing to stage (samplers live in the sampler bind group)`);
    }
    const alignment = options.alignment ?? DEFAULT_DYNAMIC_OFFSET_ALIGNMENT;
    const slotSize = roundUp(layout.structSize, alignment);
    const capacity = options.frameCapacityBytes ?? slotSize * (1 + DEFAULT_COMMAND_SLOTS);
    if (capacity < slotSize * 2) {
      throw internal(`frameCapacityBytes=${capacity} cannot hold the ${slotSize}-byte automatic block plus one command slot (${slotSize * 2} bytes needed)`);
    }
    this.layout = layout;
    this.alignment = alignment;
    this.slotSize = slotSize;
    this.ring = createRingBuffer(capacity, { alignment });
    this.ring.writeOffset = slotSize; // command slots start after the automatic block
    this.#scratch = new ArrayBuffer(layout.structSize);
  }

  /** Bytes this staging area has written into the ring (skipped scalars are not counted). */
  get bytesWritten(): number {
    return this.#bytesWritten;
  }

  /** `writeLazy` calls that changed nothing (the self-diff evidence of T076). */
  get skippedWrites(): number {
    return this.#skippedWrites;
  }

  /** Struct members the most recent write carried no value for (see the module header). */
  get missingMembers(): readonly string[] {
    return this.#missingMembers;
  }

  /** Rewind the command cursor and forget the frame's dynamic offsets (the automatic block stays). */
  beginFrame(): void {
    this.ring.writeOffset = this.slotSize;
    this.ring.dynamicOffsetsUsed.length = 0;
  }

  #absentMembers(plan: readonly UniformWritePlanEntry[]): readonly string[] {
    const written = new Set(plan.map((entry) => entry.member));
    return this.layout.members.filter((member) => !written.has(member.name)).map((member) => member.name);
  }

  /**
   * Write the automatic uniform block, copying only the scalars whose bytes changed.
   *
   * @returns whether any byte was written; `false` means the GPU buffer is already up to date.
   */
  writeLazy(values: Readonly<Record<string, unknown>>): boolean {
    const { plan } = writeStruct(this.layout, values, { into: this.#scratch });
    const ringView = new DataView(this.ring.buffer, 0, this.layout.structSize);
    const scratchView = new DataView(this.#scratch, 0, this.layout.structSize);
    let written = 0;
    for (const entry of plan) {
      const next = readScalar(scratchView, entry.byteOffset, entry.scalar);
      const current = readScalar(ringView, entry.byteOffset, entry.scalar);
      // `Object.is` (not `===`) so a NaN member is not rewritten on every frame, and `-0`/`0` — which
      // are different bit patterns — are: the comparison is about the bytes, not about JS equality.
      if (Object.is(next, current)) continue;
      writeScalar(ringView, entry.byteOffset, entry.scalar, next);
      written += 4;
    }
    this.#bytesWritten += written;
    this.#missingMembers = this.#absentMembers(plan);
    if (written === 0) {
      this.#skippedWrites += 1;
      return false;
    }
    return true;
  }

  /**
   * Write one command's manual uniforms into a fresh ring slot.
   *
   * The returned `dynamicOffset` is what the pass encoder passes to `setBindGroup(..., [offset])`; it
   * is recorded in `ring.dynamicOffsetsUsed`. A ring that cannot hold another slot raises
   * `DiagnosticError` (`internal`) naming the missing `beginFrame()` — running out of ring is a
   * frame-budget bug, not something to paper over by overwriting the previous command's data.
   */
  writeCommand(values: Readonly<Record<string, unknown>>): { readonly dynamicOffset: number; readonly bytes: Uint8Array } {
    const offset = this.ring.writeOffset;
    if (offset + this.slotSize > this.ring.frameCapacityBytes) {
      throw internal(`the uniform ring buffer is full: ${this.ring.frameCapacityBytes} bytes hold ${offset / this.slotSize} slot(s) of ${this.slotSize} and one more command needs ${this.slotSize}; call beginFrame() at the start of the frame`, {
        frameCapacityBytes: this.ring.frameCapacityBytes,
        slotSize: this.slotSize,
        requestedOffset: offset,
      });
    }
    const { bytes, plan } = writeStruct(this.layout, values, { into: this.ring.buffer, byteOffset: offset });
    this.ring.writeOffset = offset + this.slotSize;
    this.ring.dynamicOffsetsUsed.push(offset);
    this.#bytesWritten += plan.length * 4;
    this.#missingMembers = this.#absentMembers(plan);
    return { dynamicOffset: offset, bytes };
  }

  /**
   * `UniformWriteSink` implementation: write exactly one struct member into the **automatic** block.
   *
   * This is the adapter the automatic-uniform setters of the replaced `ShaderProgram` use; the
   * command-level (`command.uniformMap`) path is `writeCommand`, because those values MUST go to a
   * per-command slot with a dynamic offset (T076).
   */
  writeMember(name: string, value: unknown): void {
    const member = this.layout.members.find((candidate) => candidate.name === name);
    if (member === undefined) {
      throw internal(`"${name}" is not a member of struct "${this.layout.structName}"; the value cannot be written`);
    }
    const { plan } = writeStruct(this.layout, { [name]: value }, { into: this.ring.buffer, byteOffset: 0 });
    this.#bytesWritten += plan.length * 4;
  }
}

// ------------------------------------------------------------------------------------------------
// one member with upstream's lazy `set()` semantics
// ------------------------------------------------------------------------------------------------

export interface MemberWriteTargetOptions {
  /** Struct size of the program layout; the local buffer is allocated at this size when needed. */
  readonly structSize: number;
  /** Where changed values go. Without it the target writes into its own local buffer. */
  readonly sink?: UniformWriteSink;
  /** Local buffer to write into when there is no sink (a ring slot, or a test buffer). */
  readonly buffer?: ArrayBuffer;
}

/**
 * One uniform member with **upstream's "lazy set + self-diff"** semantics
 * (`Source/Renderer/createUniform.js`: `if (this.value !== this._value) { … gl.uniform… }`).
 *
 * The diff is taken on the **encoded** scalars, not on the JS values: a value that encodes to the
 * same bytes cannot change what the GPU reads, so it MUST NOT produce a write either. That is a
 * strictly stronger version of upstream's check (which compares raw JS values) and it is what makes
 * the per-frame automatic block free when nothing moved.
 *
 * A member that the layout does not declare (`field === undefined`) is *detached*: the layout's WGSL
 * `struct` has no such member, so the shader cannot read it and there is nothing to write — the same
 * recorded no-op as a missing value (module header). Upstream has the same situation for a uniform
 * whose `getUniformLocation()` returned `null`.
 */
export class MemberWriteTarget {
  /** The layout member this target writes, or `undefined` when the value has no struct member. */
  readonly field: UniformField | undefined;
  /** The encoded scalars of the last write (`NaN` for lanes never written) — evidence for tests. */
  readonly shadow: Float64Array;
  #sink: UniformWriteSink | undefined;
  #bytes: Uint8Array | undefined;
  #written: Uint8Array;
  #bytesWritten = 0;
  #missing = true;

  constructor(field: UniformField | undefined, options: MemberWriteTargetOptions) {
    this.field = field;
    const scalars = field === undefined ? 0 : field.length * memberElementScalars(field);
    this.shadow = new Float64Array(scalars).fill(Number.NaN);
    this.#written = new Uint8Array(scalars);
    this.#sink = options.sink;
    if (options.sink !== undefined) return;
    const buffer = options.buffer ?? new ArrayBuffer(Math.max(options.structSize, 16));
    if (buffer.byteLength < options.structSize) {
      throw internal(`the local uniform buffer is ${buffer.byteLength} byte(s) but the struct needs ${options.structSize}`);
    }
    this.#bytes = new Uint8Array(buffer, 0, options.structSize);
  }

  /** Bytes this member has written (only changed scalars are counted). */
  get bytesWritten(): number {
    return this.#bytesWritten;
  }

  /** Whether the most recent `set()` carried no value for this member (the `missingUniforms` state). */
  get missing(): boolean {
    return this.#missing;
  }

  /** Whether this member is absent from the program layout (nothing can ever be written). */
  get detached(): boolean {
    return this.field === undefined;
  }

  /**
   * Apply one value with self-diff.
   *
   * @returns `true` when bytes were written; `false` for an unchanged value, an absent value or a
   *   detached member (all three mean: the GPU buffer already holds the right bytes).
   */
  set(value: unknown): boolean {
    const field = this.field;
    if (field === undefined) {
      this.#missing = true;
      return false;
    }
    const plan = encodeMember(field, value);
    this.#missing = plan.length === 0;
    if (plan.length === 0) return false; // absent value: recorded no-write, never a NaN write
    const scalarsPerElement = memberElementScalars(field);
    const changed: UniformWritePlanEntry[] = [];
    for (const entry of plan) {
      const index = entry.element * scalarsPerElement + entry.column * field.components + entry.component;
      if (this.#written[index] === 1 && Object.is(this.shadow[index], entry.value)) continue;
      changed.push(entry);
    }
    if (changed.length === 0) return false;
    if (this.#sink !== undefined) this.#sink.writeMember(field.name, value);
    else applyPlan(changed, this.#bytes as Uint8Array);
    for (const entry of changed) {
      const index = entry.element * scalarsPerElement + entry.column * field.components + entry.component;
      this.shadow[index] = entry.value;
      this.#written[index] = 1;
    }
    this.#bytesWritten += changed.length * 4;
    return true;
  }
}
