/**
 * @license
 * Copyright 2011-2024 CesiumJS Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Modified for WebGPU backend: module-level replacement of `Source/Renderer/createUniform.js`
 * (kind: "replace") in the cesium-webgpu patch layer.
 * Upstream baseline: @cesium/engine 26.3.0 — see upstream/engine-26.3.0.lock.json and
 * packages/cesium-webgpu/backend-webgpu/manifest.json.
 *
 * WHY THIS IS A REPLACEMENT AND NOT A TRANSLATION (tasks.md **T076**, FR-030)
 *   Upstream generates one object per active uniform whose `set()` calls `gl.uniform*` at a
 *   `WebGLUniformLocation`. WebGPU has neither entry point: a value travels as bytes in a uniform
 *   buffer whose WGSL `struct` is generated by `webgpu/bind-layout.ts` (research §5.4, data-model
 *   §4.3), and a `sampler2D` is not a struct member at all — it is a texture/sampler pair in its own
 *   bind group.
 *
 *   What MUST stay exactly upstream is the **call shape** and the **setter object shape**, because the
 *   logic layer and the replaced `Renderer/ShaderProgram` drive them:
 *
 *     createUniform(gl, activeUniform, uniformName, location)
 *       → { name, value, set(), [_setSampler], [textureUnitIndex], [_locations] }
 *
 *   and the **lazy set + self-diff** semantic: assigning a value equal to the one already staged MUST
 *   NOT write anything (`webgpu/uniform-writer.ts` `MemberWriteTarget`). The diff is taken on the
 *   *encoded* bytes rather than on the JS value, which is strictly stronger: two values that encode
 *   identically cannot change what the GPU reads.
 *
 * LAYOUT OWNERSHIP — `{ layout, writer }` (T076)
 *   - `options.layout` (`BindLayoutResult` of `webgpu/bind-layout.ts`) is the ONLY source of types and
 *     offsets; `activeUniform` then serves as evidence (name/GL enum) and is never parsed for layout.
 *   - `options.writer` is the sink changed values are pushed into (`UniformStaging` implements it).
 *     Without a writer the setter owns a **local** struct buffer it really encodes into — the
 *     standalone "no-GPU" mode the unit suite uses; the bytes are reachable through `_buffer`.
 *   - Without a layout the setter builds an **implicit** single-member layout from `activeUniform`
 *     (GL type enum → GLSL type → `layoutUniforms`), so the standalone mode exercises the same code
 *     path instead of a parallel one. A uniform type `bind-layout.ts` does not know raises
 *     `not-implemented` — a guess would be a silently wrong struct.
 *   - A name the supplied layout does not declare is **detached**: the WGSL `struct` has no such
 *     member, so nothing can read it and nothing is written (`_detachedReason` records why). This is
 *     upstream's behaviour for a uniform whose `getUniformLocation()` returned `null`, and it mirrors
 *     the missing-member rule of the writer (see its module header / `tools/shader-verify.mjs`).
 *
 * Samplers: the setter keeps upstream's texture-unit bookkeeping (`_setSampler`, `textureUnitIndex`)
 * so `ShaderProgram` can still count texture units, but `set()` cannot bind anything on the CPU side:
 * unless the injected writer implements `writeSampler`, it raises `not-implemented` naming the phase
 * that assembles the texture/sampler bind group. Returning silently would be a black frame with no
 * diagnostic (contract render-path-api §6, FR-033).
 */
import { DiagnosticError, throwNotImplemented } from "../webgpu/errors.js";
import { layoutUniforms } from "../webgpu/bind-layout.js";
import type { BindLayoutResult, SamplerBinding, UniformField } from "../webgpu/bind-layout.js";
import { MemberWriteTarget } from "../webgpu/uniform-writer.js";
import type { UniformWriteSink } from "../webgpu/uniform-writer.js";

const UPSTREAM_MODULE = "Renderer/createUniform.js";

/**
 * GL `WebGLActiveInfo.type` enums (fixed by the GL ES 3.0 spec) → the GLSL type name bind-layout
 * understands. The constants are spelled out instead of read from a `gl` context so that this module
 * stays usable without a GL context — the WebGPU backend never creates one.
 */
export const GLSL_TYPE_BY_GL_ENUM: Readonly<Record<number, string>> = {
  0x1406: "float",
  0x8b50: "vec2",
  0x8b51: "vec3",
  0x8b52: "vec4",
  0x1404: "int",
  0x8b53: "ivec2",
  0x8b54: "ivec3",
  0x8b55: "ivec4",
  0x8b56: "bool",
  0x8b57: "bvec2",
  0x8b58: "bvec3",
  0x8b59: "bvec4",
  0x8b5a: "mat2",
  0x8b5b: "mat3",
  0x8b5c: "mat4",
  0x8b5e: "sampler2D",
  0x8b5f: "sampler3D",
  0x8b60: "samplerCube",
};

/**
 * The part of the GL `WebGLActiveInfo` this module consumes, plus the WebGPU-flavoured escape hatch
 * (`glslType`) the replaced `ShaderProgram` can supply straight from the assembled GLSL declaration.
 */
export interface ActiveUniformDescriptor {
  readonly name?: string;
  /** A `gl.FLOAT`/`gl.FLOAT_VEC3`/… enum; only used when no `layout` is supplied. */
  readonly type?: number;
  /** GLSL array length (`WebGLActiveInfo.size`); 1 for a non-array uniform. */
  readonly size?: number;
  /** The GLSL type name (`"vec3"`, `"mat3"`, `"sampler2D"`, …) — wins over `type`. */
  readonly glslType?: string;
}

export interface CreateUniformOptions {
  /** The program's layout; the only source of member types and byte offsets. */
  readonly layout?: BindLayoutResult;
  /** Sink for changed values; `UniformStaging` (automatic block) implements it. */
  readonly writer?: UniformWriteSink;
}

/** The numeric setter shape upstream returns (plus the writer evidence this backend adds). */
export interface NumericUniformSetter {
  name: string;
  value: unknown;
  set(): void;
  readonly _gl: unknown;
  readonly _location: unknown;
  /** The member-level lazy writer (self-diff + offsets) behind this setter. */
  readonly _target: MemberWriteTarget;
  /** The local struct buffer in standalone (no writer) mode, `undefined` otherwise. */
  readonly _buffer: ArrayBuffer | undefined;
  /** Why this uniform is not a member of the program layout, if it is not. */
  readonly _detachedReason: string | undefined;
  readonly _bytesWritten: number;
}

/** The sampler setter shape upstream returns (see the module header for the `set()` contract). */
export interface SamplerUniformSetter {
  name: string;
  value: unknown;
  set(): void;
  /** Upstream keeps one location for a single sampler and all of them for an array sampler. */
  readonly _locations?: readonly unknown[];
  textureUnitIndex: number | undefined;
  _setSampler(textureUnitIndex: number): number;
  readonly _gl: unknown;
  readonly _location: unknown;
}

export type UniformSetter = NumericUniformSetter | SamplerUniformSetter;

function internalError(message: string): DiagnosticError {
  return new DiagnosticError("internal", `createUniform: ${message}`, {
    backend: "webgpu",
    upstreamModule: UPSTREAM_MODULE,
    requirementRef: "FR-030",
  });
}

/** GLSL type of the descriptor, or `not-implemented` when this slice cannot express it in WGSL. */
function glslTypeOf(descriptor: ActiveUniformDescriptor, uniformName: string, entryPoint: string): string {
  if (typeof descriptor.glslType === "string" && descriptor.glslType.length > 0) return descriptor.glslType;
  const glEnum = descriptor.type;
  const glslType = typeof glEnum === "number" ? GLSL_TYPE_BY_GL_ENUM[glEnum] : undefined;
  if (glslType === undefined) {
    return throwNotImplemented(`the uniform type of "${uniformName}" (GL enum ${glEnum === undefined ? "(none)" : `0x${glEnum.toString(16)}`})`, {
      backend: "webgpu",
      upstreamModule: UPSTREAM_MODULE,
      entryPoint,
      requirementRef: "FR-030",
      plannedPhase: "a slice that maps this GLSL uniform type onto a WGSL/WebGPU uniform",
      extra: { uniform: uniformName, glEnum: typeof glEnum === "number" ? glEnum : -1 },
    });
  }
  return glslType;
}

/**
 * The standalone "no-GPU" layout: one uniform, laid out by the same generator the real program uses.
 */
function implicitLayout(uniformName: string, descriptor: ActiveUniformDescriptor, size: number, entryPoint: string): BindLayoutResult {
  const glslType = glslTypeOf(descriptor, uniformName, entryPoint);
  try {
    return layoutUniforms([{ name: uniformName, glslType, size }]);
  } catch (cause) {
    return throwNotImplemented(`the uniform type "${glslType}" of "${uniformName}"`, {
      backend: "webgpu",
      upstreamModule: UPSTREAM_MODULE,
      entryPoint,
      requirementRef: "FR-030",
      plannedPhase: "a slice that maps this GLSL uniform type onto a WGSL/WebGPU uniform",
      cause,
    });
  }
}

interface ResolvedMember {
  readonly layout: BindLayoutResult;
  readonly field: UniformField | undefined;
  readonly sampler: SamplerBinding | undefined;
  readonly detachedReason: string | undefined;
}

function resolveMember(uniformName: string, descriptor: ActiveUniformDescriptor, options: CreateUniformOptions): ResolvedMember {
  const layout = options.layout;
  if (layout === undefined) {
    const implicit = implicitLayout(uniformName, descriptor, Math.max(1, descriptor.size ?? 1), "createUniform");
    const sampler = implicit.samplers[0];
    if (sampler !== undefined) return { layout: implicit, field: undefined, sampler, detachedReason: undefined };
    const field = implicit.members[0];
    if (field === undefined) throw internalError(`the implicit layout of "${uniformName}" declares neither a member nor a sampler`);
    return { layout: implicit, field, sampler: undefined, detachedReason: undefined };
  }
  const sampler = layout.samplers.find((candidate) => candidate.name === uniformName || candidate.glslName === uniformName);
  if (sampler !== undefined) return { layout, field: undefined, sampler, detachedReason: undefined };
  const field = layout.members.find((candidate) => candidate.name === uniformName);
  if (field !== undefined) return { layout, field, sampler: undefined, detachedReason: undefined };
  return {
    layout,
    field: undefined,
    sampler: undefined,
    detachedReason: `struct "${layout.structName}" declares no uniform "${uniformName}", so no WGSL statement can read it and no byte is written`,
  };
}

/**
 * Upstream entry point `createUniform(…)`.
 *
 * @param {WebGL2RenderingContext} gl kept for call-site fidelity; never used (WebGPU has no GL).
 * @param {WebGLActiveInfo} activeUniform the uniform's GL descriptor, or `{ glslType }`.
 * @param {string} uniformName the uniform's name.
 * @param {WebGLUniformLocation} location kept for call-site fidelity (upstream reports it here).
 * @param {object} [options] `{ layout, writer }` — see the module header.
 * @returns {object} the setter object `ShaderProgram` drives.
 * @private
 */
export default function createUniform(gl: unknown, activeUniform: ActiveUniformDescriptor, uniformName: string, location: unknown, options: CreateUniformOptions = {}): UniformSetter {
  // A missing argument is a wiring error, and it MUST be diagnosable: a raw `TypeError` from reading
  // `.type` of `undefined` is exactly the failure mode contract render-path-api §6 forbids.
  if (activeUniform === undefined || activeUniform === null) {
    throw internalError("the uniform descriptor (upstream's WebGLActiveInfo) is required but was not provided");
  }
  if (typeof uniformName !== "string" || uniformName.length === 0) {
    throw internalError(`the uniform name is required but was ${typeof uniformName === "string" ? "empty" : `a ${typeof uniformName}`}`);
  }
  const resolved = resolveMember(uniformName, activeUniform, options);
  if (resolved.sampler !== undefined) {
    return new SamplerUniform(uniformName, gl, location, options.writer, 1);
  }
  const field = resolved.field;
  // `field === undefined` with a reason is the *detached* case (the layout has no such member, so no
  // WGSL statement can read it): the setter is built and records why nothing is ever written.
  if (field === undefined && resolved.detachedReason === undefined) {
    throw internalError(`"${uniformName}" resolved to neither a member nor a sampler`);
  }
  const structSize = resolved.layout.structSize;
  let buffer: ArrayBuffer | undefined;
  let target: MemberWriteTarget;
  if (options.writer === undefined) {
    buffer = new ArrayBuffer(Math.max(structSize, 16));
    target = new MemberWriteTarget(field, { structSize, buffer });
  } else {
    target = new MemberWriteTarget(field, { structSize, sink: options.writer });
  }
  return new NumericUniform(uniformName, gl, location, target, buffer, resolved.detachedReason);
}

/** `UniformFloat`/`UniformInt`/`UniformMat*`: one member, lazy `set()`, no GL call. */
class NumericUniform implements NumericUniformSetter {
  name: string;
  value: unknown = undefined;
  readonly _gl: unknown;
  readonly _location: unknown;
  readonly _target: MemberWriteTarget;
  readonly _buffer: ArrayBuffer | undefined;
  readonly _detachedReason: string | undefined;

  constructor(name: string, gl: unknown, location: unknown, target: MemberWriteTarget, buffer: ArrayBuffer | undefined, detachedReason: string | undefined) {
    this.name = name;
    this._gl = gl;
    this._location = location;
    this._target = target;
    this._buffer = buffer;
    this._detachedReason = detachedReason;
  }

  get _bytesWritten(): number {
    return this._target.bytesWritten;
  }

  set(): void {
    this._target.set(this.value);
  }
}

/** `UniformSampler`: texture-unit bookkeeping only — binding happens in the sampler bind group. */
class SamplerUniform implements SamplerUniformSetter {
  name: string;
  value: unknown = undefined;
  textureUnitIndex: number | undefined = undefined;
  readonly _gl: unknown;
  readonly _location: unknown;
  readonly #sink: UniformWriteSink | undefined;
  readonly #length: number;

  constructor(name: string, gl: unknown, location: unknown, sink: UniformWriteSink | undefined, length: number) {
    this.name = name;
    this._gl = gl;
    this._location = location;
    this.#sink = sink;
    this.#length = length;
  }

  set(): void {
    const sink = this.#sink;
    if (sink !== undefined && sink.writeSampler !== undefined) {
      sink.writeSampler(this.name, this.value);
      return;
    }
    return throwNotImplemented(`binding the sampler uniform "${this.name}" to its texture`, {
      backend: "webgpu",
      upstreamModule: UPSTREAM_MODULE,
      entryPoint: "UniformSampler#set",
      requirementRef: "FR-030",
      plannedPhase: "W4 (T075: Renderer/ShaderProgram assembles the texture/sampler bind group)",
      extra: { uniform: this.name, textureUnitIndex: this.textureUnitIndex ?? -1 },
    });
  }

  _setSampler(textureUnitIndex: number): number {
    this.textureUnitIndex = textureUnitIndex;
    return textureUnitIndex + this.#length;
  }
}
