// ============================================================================================
// cesium-webgpu WebGPU backend layer — frozen reference module pair (tasks.md T069).
//
// GENERATED by `node tools/scripts/gen-reference-modules.mjs`; the unit suite runs it with
// `--check`, so this file can never silently drift from the emitter.
//
// Variant: textureUnits=1|quantization=float|lighting=daynight|groundAtmosphere=none|fog=none|ocean=none|imageryOps=none|tileLimitRectangle=none|geodetic=none
// Defines: INCLUDE_WEB_MERCATOR_Y TEXTURE_UNITS 1 ENABLE_DAYNIGHT_SHADING
// Layout: union over the MVP-reachable define space (53 struct members + 3 sampler bindings).
//
// Why it is checked in: `wgsl/leaves/**` are templates (`#if` directives that WGSL does not have),
// so a module-level validator cannot read them. This pair is complete and template-free, which is
// what `tools/scripts/check-wgsl.mjs` hands to `naga --input-kind wgsl`, and what architecture rule
// A10 pairs up statically (`-vs` output locations vs `-fs` input locations).
// ============================================================================================
// Generated by packages/cesium-webgpu/backend-webgpu/webgpu/wgsl-emitter.ts (tasks.md T073/T074).
// Module-static upstream defines: INCLUDE_WEB_MERCATOR_Y ENABLE_DAYNIGHT_SHADING
// Pipeline-overridable constants (NOT part of this text — see the declarations below): numberOfDayTextures, perFragmentGroundAtmosphere
// Varying set (derived from the real assembled GLSL, not from the WGSL): v_positionMC@0 v_textureCoordinates@2

// Pipeline-overridable constants (G-6/T025): the two dimensions that change **inside a frame**
// live here, not in the module text, so a new value is a pipeline specialisation on this parsed
// module instead of a new module. Declared in both stages because the pipeline `constants` map is
// per pipeline, and a key a module does not declare is a validation error.
override numberOfDayTextures : u32 = 0u;
override perFragmentGroundAtmosphere : u32 = 0u;

const czm_sceneMode2D: f32 = 2.0;
const czm_sceneMode3D: f32 = 3.0;
const czm_sceneModeColumbusView: f32 = 1.0;
fn czms_remapClipDepth(position: vec4<f32>) -> vec4<f32> {
  return vec4<f32>(position.x, position.y, 0.5 * position.z + 0.5 * position.w, position.w);
}

fn czms_unprojectDepth(ndcDepth: f32) -> f32 {
  return 2.0 * ndcDepth - 1.0;
}

fn czms_gammaCorrect4(color: vec4<f32>) -> vec4<f32> {
  return color;
}

fn czms_getLambertDiffuse(lightDirectionEC: vec3<f32>, normalEC: vec3<f32>) -> f32 {
  return max(dot(lightDirectionEC, normalEC), 0.0);
}

fn czms_geodeticSurfaceNormal(positionOnEllipsoid: vec3<f32>, ellipsoidCenter: vec3<f32>, oneOverEllipsoidRadiiSquared: vec3<f32>) -> vec3<f32> {
  return normalize((positionOnEllipsoid - ellipsoidCenter) * oneOverEllipsoidRadiiSquared);
}

struct TerrainUniforms {
  czm_currentFrustum : vec2<f32>,
  czm_ellipsoidInverseRadii : vec3<f32>,
  czm_ellipsoidRadii : vec3<f32>,
  czm_eyeHeight : f32,
  czm_fogDensity : f32,
  czm_fogVisualDensityScalar : f32,
  czm_frameNumber : f32,
  czm_frustumPlanes : vec4<f32>,
  czm_gamma : f32,
  czm_inverseModelView : mat4x4<f32>,
  czm_inverseView : mat4x4<f32>,
  czm_lightColor : vec3<f32>,
  czm_lightDirectionEC : vec3<f32>,
  czm_lightDirectionWC : vec3<f32>,
  czm_modelView : mat4x4<f32>,
  czm_modelView3D : mat4x4<f32>,
  czm_morphTime : f32,
  czm_normal3D : mat3x3<f32>,
  czm_orthographicIn3D : f32,
  czm_pixelRatio : f32,
  czm_projection : mat4x4<f32>,
  czm_sceneMode : f32,
  czm_splitPosition : f32,
  czm_sunDirectionWC : vec3<f32>,
  czm_view : mat4x4<f32>,
  czm_viewerPositionWC : vec3<f32>,
  czm_viewport : vec4<f32>,
  u_atmosphereLightIntensity : f32,
  u_atmosphereMieAnisotropy : f32,
  u_atmosphereMieCoefficient : vec3<f32>,
  u_atmosphereMieScaleHeight : f32,
  u_atmosphereRayleighCoefficient : vec3<f32>,
  u_atmosphereRayleighScaleHeight : f32,
  u_center3D : vec3<f32>,
  u_dayTextureAlpha : array<vec4<f32>, 3>,
  u_dayTextureTexCoordsRectangle : array<vec4<f32>, 3>,
  u_dayTextureTranslationAndScale : array<vec4<f32>, 3>,
  u_dayTextureUseWebMercatorT : array<vec4<u32>, 3>,
  u_initialColor : vec4<f32>,
  u_lambertDiffuseMultiplier : f32,
  u_lightingFadeDistance : vec2<f32>,
  u_minimumBrightness : f32,
  u_minMaxHeight : vec2<f32>,
  u_modifiedModelView : mat4x4<f32>,
  u_modifiedModelViewProjection : mat4x4<f32>,
  u_nightFadeDistance : vec2<f32>,
  u_radiiAndDynamicAtmosphereColor : vec3<f32>,
  u_scaleAndBias : mat4x4<f32>,
  u_southAndNorthLatitude : vec2<f32>,
  u_southMercatorYAndOneOverHeight : vec2<f32>,
  u_tileRectangle : vec4<f32>,
  u_vertexShadowDarkness : f32,
  u_verticalExaggerationAndRelativeHeight : vec2<f32>,
}


@group(0) @binding(0) var<uniform> czm : TerrainUniforms;
@group(1) @binding(1) var u_dayTextures_0_texture : texture_2d<f32>;
@group(1) @binding(2) var u_dayTextures_0_sampler : sampler;
@group(1) @binding(3) var u_dayTextures_1_texture : texture_2d<f32>;
@group(1) @binding(4) var u_dayTextures_1_sampler : sampler;
@group(1) @binding(5) var u_dayTextures_2_texture : texture_2d<f32>;
@group(1) @binding(6) var u_dayTextures_2_sampler : sampler;
struct FSIn {
  @builtin(position) position : vec4<f32>,
  @builtin(front_facing) front_facing : bool,
  @location(0) v_positionMC : vec3<f32>,
  @location(2) v_textureCoordinates : vec3<f32>,
}

fn sampleAndBlend(
  previousColor: vec4<f32>,
  textureToSample: texture_2d<f32>,
  textureSampler: sampler,
  tileTextureCoordinates: vec2<f32>,
  textureCoordinateRectangle: vec4<f32>,
  textureCoordinateTranslationAndScale: vec4<f32>,
  textureAlphaIn: f32,
  textureNightAlpha: f32,
  textureDayAlpha: f32,
  textureBrightness: f32,
  textureContrast: f32,
  textureHue: f32,
  textureSaturation: f32,
  textureOneOverGamma: f32,
  split: f32,
  colorToAlpha: vec4<f32>,
  nightBlend: f32,
  fragCoordX: f32,
) -> vec4<f32> {
  var textureAlpha = textureAlphaIn;
  var alphaMultiplier = step(textureCoordinateRectangle.xy, tileTextureCoordinates);
  textureAlpha = textureAlpha * alphaMultiplier.x * alphaMultiplier.y;
  alphaMultiplier = step(vec2<f32>(0.0, 0.0), textureCoordinateRectangle.zw - tileTextureCoordinates);
  textureAlpha = textureAlpha * alphaMultiplier.x * alphaMultiplier.y;

  let translation = textureCoordinateTranslationAndScale.xy;
  let scale = textureCoordinateTranslationAndScale.zw;
  let textureCoordinates = tileTextureCoordinates * scale + translation;
  let value = textureSampleLevel(textureToSample, textureSampler, textureCoordinates, 0.0);
  var color = value.rgb;
  var alpha = value.a;

  let tempColor = czms_gammaCorrect4(vec4<f32>(color, alpha));
  color = tempColor.rgb;
  alpha = tempColor.a;

  let sourceAlpha = alpha * textureAlpha;
  var outAlpha = mix(previousColor.a, 1.0, sourceAlpha);
  outAlpha = outAlpha + (sign(outAlpha) - 1.0);
  let outColor = mix(previousColor.rgb * previousColor.a, color, sourceAlpha) / outAlpha;
  return vec4<f32>(outColor, max(outAlpha, 0.0));
}

fn computeDayColor(initialColor: vec4<f32>, textureCoordinates: vec3<f32>, nightBlend: f32, fragCoordX: f32) -> vec4<f32> {
  var color = initialColor;
  if (numberOfDayTextures > 0u) {
  color = sampleAndBlend(
    color,
    u_dayTextures_0_texture,
    u_dayTextures_0_sampler,
    select(textureCoordinates.xy, textureCoordinates.xz, czm.u_dayTextureUseWebMercatorT[0].x != 0u),
    czm.u_dayTextureTexCoordsRectangle[0],
    czm.u_dayTextureTranslationAndScale[0],
    1.0,
    1.0,
    1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    vec4<f32>(0.0),
    nightBlend,
    fragCoordX,
  );
  }
  if (numberOfDayTextures > 1u) {
  color = sampleAndBlend(
    color,
    u_dayTextures_1_texture,
    u_dayTextures_1_sampler,
    select(textureCoordinates.xy, textureCoordinates.xz, czm.u_dayTextureUseWebMercatorT[1].x != 0u),
    czm.u_dayTextureTexCoordsRectangle[1],
    czm.u_dayTextureTranslationAndScale[1],
    1.0,
    1.0,
    1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    vec4<f32>(0.0),
    nightBlend,
    fragCoordX,
  );
  }
  if (numberOfDayTextures > 2u) {
  color = sampleAndBlend(
    color,
    u_dayTextures_2_texture,
    u_dayTextures_2_sampler,
    select(textureCoordinates.xy, textureCoordinates.xz, czm.u_dayTextureUseWebMercatorT[2].x != 0u),
    czm.u_dayTextureTexCoordsRectangle[2],
    czm.u_dayTextureTranslationAndScale[2],
    1.0,
    1.0,
    1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    vec4<f32>(0.0),
    nightBlend,
    fragCoordX,
  );
  }
  return color;
}

@fragment
fn fs_main(input: FSIn) -> @location(0) vec4<f32> {

  let normalMC = czms_geodeticSurfaceNormal(input.v_positionMC, vec3<f32>(0.0), vec3<f32>(1.0));
  let normalEC = czm.czm_normal3D * normalMC;

  let nightBlend = 0.0;

  let clampedTexCoords = clamp(input.v_textureCoordinates, vec3<f32>(0.0, 0.0, 0.0), vec3<f32>(1.0, 1.0, 1.0));
  var color = computeDayColor(czm.u_initialColor, clampedTexCoords, nightBlend, input.position.x);

  var cameraDist: f32;
  if (czm.czm_sceneMode == czm_sceneMode2D) {
    cameraDist = max(czm.czm_frustumPlanes.x - czm.czm_frustumPlanes.y, czm.czm_frustumPlanes.w - czm.czm_frustumPlanes.z) * 0.5;
  } else if (czm.czm_sceneMode == czm_sceneModeColumbusView) {
    cameraDist = -czm.czm_view[3].z;
  } else {
    cameraDist = length(czm.czm_view[3].xyz);
  }
  var fadeOutDist = czm.u_lightingFadeDistance.x;
  var fadeInDist = czm.u_lightingFadeDistance.y;
  if (czm.czm_sceneMode != czm_sceneMode3D) {
    let radii = czm.czm_ellipsoidRadii;
    let maxRadii = max(radii.x, max(radii.y, radii.z));
    fadeOutDist = fadeOutDist - maxRadii;
    fadeInDist = fadeInDist - maxRadii;
  }
  let fade = clamp((cameraDist - fadeOutDist) / (fadeInDist - fadeOutDist), 0.0, 1.0);

  let diffuseIntensity = clamp(czms_getLambertDiffuse(czm.czm_lightDirectionEC, normalEC) * 5.0 + 0.3, 0.0, 1.0);
  var finalColor = vec4<f32>(color.rgb * czm.czm_lightColor * mix(1.0, diffuseIntensity, fade), color.a);

  let atmosphereLightDirection = czm.czm_lightDirectionWC;

  return finalColor;
}

