// ============================================================================================
// cesium-webgpu WebGPU backend layer — frozen reference module pair (tasks.md T069).
//
// GENERATED by `node tools/scripts/gen-reference-modules.mjs`; the unit suite runs it with
// `--check`, so this file can never silently drift from the emitter.
//
// Variant: textureUnits=1|quantization=float|lighting=daynight|groundAtmosphere=none|fog=none|ocean=none|imageryOps=none|tileLimitRectangle=none|geodetic=none
// Defines: INCLUDE_WEB_MERCATOR_Y TEXTURE_UNITS 1 ENABLE_DAYNIGHT_SHADING
// Layout: union over the MVP-reachable define space (53 struct members + 3 sampler bindings).
//
// Why it is checked in: `wgsl/leaves/**` are templates (`#if` directives that WGSL does not have),
// so a module-level validator cannot read them. This pair is complete and template-free, which is
// what `tools/scripts/check-wgsl.mjs` hands to `naga --input-kind wgsl`, and what architecture rule
// A10 pairs up statically (`-vs` output locations vs `-fs` input locations).
// ============================================================================================
// Generated by packages/cesium-webgpu/backend-webgpu/webgpu/wgsl-emitter.ts (tasks.md T073/T074).
// Module-static upstream defines: INCLUDE_WEB_MERCATOR_Y ENABLE_DAYNIGHT_SHADING
// Pipeline-overridable constants (NOT part of this text — see the declarations below): numberOfDayTextures, perFragmentGroundAtmosphere
// Varying set (derived from the real assembled GLSL, not from the WGSL): v_positionMC@0 v_textureCoordinates@2

// Pipeline-overridable constants (G-6/T025): the two dimensions that change **inside a frame**
// live here, not in the module text, so a new value is a pipeline specialisation on this parsed
// module instead of a new module. Declared in both stages because the pipeline `constants` map is
// per pipeline, and a key a module does not declare is a validation error.
override numberOfDayTextures : u32 = 0u;
override perFragmentGroundAtmosphere : u32 = 0u;

fn czms_remapClipDepth(position: vec4<f32>) -> vec4<f32> {
  return vec4<f32>(position.x, position.y, 0.5 * position.z + 0.5 * position.w, position.w);
}

fn czms_unprojectDepth(ndcDepth: f32) -> f32 {
  return 2.0 * ndcDepth - 1.0;
}

struct TerrainUniforms {
  czm_currentFrustum : vec2<f32>,
  czm_ellipsoidInverseRadii : vec3<f32>,
  czm_ellipsoidRadii : vec3<f32>,
  czm_eyeHeight : f32,
  czm_fogDensity : f32,
  czm_fogVisualDensityScalar : f32,
  czm_frameNumber : f32,
  czm_frustumPlanes : vec4<f32>,
  czm_gamma : f32,
  czm_inverseModelView : mat4x4<f32>,
  czm_inverseView : mat4x4<f32>,
  czm_lightColor : vec3<f32>,
  czm_lightDirectionEC : vec3<f32>,
  czm_lightDirectionWC : vec3<f32>,
  czm_modelView : mat4x4<f32>,
  czm_modelView3D : mat4x4<f32>,
  czm_morphTime : f32,
  czm_normal3D : mat3x3<f32>,
  czm_orthographicIn3D : f32,
  czm_pixelRatio : f32,
  czm_projection : mat4x4<f32>,
  czm_sceneMode : f32,
  czm_splitPosition : f32,
  czm_sunDirectionWC : vec3<f32>,
  czm_view : mat4x4<f32>,
  czm_viewerPositionWC : vec3<f32>,
  czm_viewport : vec4<f32>,
  u_atmosphereLightIntensity : f32,
  u_atmosphereMieAnisotropy : f32,
  u_atmosphereMieCoefficient : vec3<f32>,
  u_atmosphereMieScaleHeight : f32,
  u_atmosphereRayleighCoefficient : vec3<f32>,
  u_atmosphereRayleighScaleHeight : f32,
  u_center3D : vec3<f32>,
  u_dayTextureAlpha : array<vec4<f32>, 3>,
  u_dayTextureTexCoordsRectangle : array<vec4<f32>, 3>,
  u_dayTextureTranslationAndScale : array<vec4<f32>, 3>,
  u_dayTextureUseWebMercatorT : array<vec4<u32>, 3>,
  u_initialColor : vec4<f32>,
  u_lambertDiffuseMultiplier : f32,
  u_lightingFadeDistance : vec2<f32>,
  u_minimumBrightness : f32,
  u_minMaxHeight : vec2<f32>,
  u_modifiedModelView : mat4x4<f32>,
  u_modifiedModelViewProjection : mat4x4<f32>,
  u_nightFadeDistance : vec2<f32>,
  u_radiiAndDynamicAtmosphereColor : vec3<f32>,
  u_scaleAndBias : mat4x4<f32>,
  u_southAndNorthLatitude : vec2<f32>,
  u_southMercatorYAndOneOverHeight : vec2<f32>,
  u_tileRectangle : vec4<f32>,
  u_vertexShadowDarkness : f32,
  u_verticalExaggerationAndRelativeHeight : vec2<f32>,
}


@group(0) @binding(0) var<uniform> czm : TerrainUniforms;
@group(1) @binding(1) var u_dayTextures_0_texture : texture_2d<f32>;
@group(1) @binding(2) var u_dayTextures_0_sampler : sampler;
@group(1) @binding(3) var u_dayTextures_1_texture : texture_2d<f32>;
@group(1) @binding(4) var u_dayTextures_1_sampler : sampler;
@group(1) @binding(5) var u_dayTextures_2_texture : texture_2d<f32>;
@group(1) @binding(6) var u_dayTextures_2_sampler : sampler;
struct VSIn {
  @location(0) position3DAndHeight : vec4<f32>,
  @location(1) textureCoordAndEncodedNormals : vec4<f32>,
}

struct VSOut {
  @builtin(position) position : vec4<f32>,
  @location(0) v_positionMC : vec3<f32>,
  @location(2) v_textureCoordinates : vec3<f32>,
}

fn getPosition3DMode(position: vec3<f32>, height: f32, textureCoordinates: vec2<f32>) -> vec4<f32> {
  return czm.u_modifiedModelViewProjection * vec4<f32>(position, 1.0);
}

fn getPosition(position: vec3<f32>, height: f32, textureCoordinates: vec2<f32>) -> vec4<f32> { return getPosition3DMode(position, height, textureCoordinates); }

@vertex
fn vs_main(input: VSIn) -> VSOut {
  var position: vec3<f32>;
  var height: f32;
  var textureCoordinates: vec2<f32>;
  var webMercatorT: f32;
  var encodedNormal: f32;

  position = input.position3DAndHeight.xyz;
  height = input.position3DAndHeight.w;
  textureCoordinates = input.textureCoordAndEncodedNormals.xy;

  webMercatorT = input.textureCoordAndEncodedNormals.z;
  encodedNormal = 0.0;

  var position3DWC = position + czm.u_center3D;

  let ellipsoidNormal = normalize(position3DWC);

  var out: VSOut;
  
  out.position = czms_remapClipDepth(getPosition(position, height, textureCoordinates));

  out.v_positionMC = position3DWC; 

  out.v_textureCoordinates = vec3<f32>(textureCoordinates, webMercatorT);

  return out;
}

