/**
 * SPDX-License-Identifier: Apache-2.0
 *
 * New module of the cesium-webgpu render backend layer (not derived from any upstream file).
 *
 * **WGSL `czm_` prelude library** (tasks.md **T068**; contract fork-patch-layer §5 rule **R3**;
 * data-model §4.5 `WgslPreludeEntry`).
 *
 * The `czm_` built-ins the terrain shader closure needs (the terrain subset of the 72 `czm_`
 * references a default terrain pair makes, ≈40 upstream names — 38 functions + 11 constants +
 * 3 structs + 38 automatic-uniform members in the generated catalog) live here, **not** under
 * `Source/Shaders/**`: the upstream shader tree stays byte-identical (contract §9 MUST NOT).
 *
 * The prelude is prepended to **every** emitted WGSL module, and the emitter then prunes the
 * declarations the entry point cannot reach (`wgsl-prune.ts`, G-6 fix (b)) — so the text is one
 * source of truth while the shipped module carries only what it uses.
 *
 * **Overload splitting (WGSL has no function overloading).** Upstream declares
 * `czm_signNotZero(float|vec2|vec3|vec4)`, `czm_octDecode(vec2|float)`, `czm_fog` (arity 3/4), …;
 * the port gives each overload its own WGSL name and records the mapping in `catalog.json`
 * (generated by `tools/scripts/gen-wgsl-catalog.mjs`, mirrored into `catalog.ts` for the browser
 * bundle). `preludeFor()` is the lookup; an unknown name is an error, never a silent skip.
 *
 * Zero `node:` import in the runtime path: the prelude text is inlined by
 * `tools/scripts/gen-wgsl-library.mjs` into `wgsl/generated-library.ts`. The `node:fs`-based loader
 * lives in `wgsl/index.ts` and is only used by tools and tests.
 */
import { PRELUDE_CATALOG_ENTRIES } from "./catalog.js";

/** `data-model §4.5 WgslPreludeEntry`. */
export interface WgslPreludeEntry {
  /** The upstream GLSL name, without argument list: `czm_signNotZero`. */
  readonly czmName: string;
  /** The WGSL name (or `czm.<member>` for an automatic uniform) — distinct per overload. */
  readonly wgslName: string;
  readonly kind: "constant" | "function" | "struct" | "builtin";
  /** The arity that distinguishes this row from the other overloads of `czmName` (`null` = the base form). */
  readonly overload: number | null;
  /** Where the upstream declaration lives (traceability for R7's drift detection). */
  readonly upstream: string;
}

/** A prelude fragment: the WGSL text plus the upstream leaf it replaces. */
export interface PreludeFragment {
  /** Upstream leaf name, e.g. `czm_signNotZero` (one fragment per overload family). */
  readonly name: string;
  /** Hash of the upstream leaf text this fragment is the translation of (contract §5 R7). */
  readonly leafHash: string;
  readonly wgsl: string;
  /** Every catalog row this fragment carries (a family with N overloads carries N rows). */
  readonly entries: readonly WgslPreludeEntry[];
}

/** The generated `czmName → wgslName` table (90 rows for the terrain closure). */
export const PRELUDE_CATALOG: readonly WgslPreludeEntry[] = PRELUDE_CATALOG_ENTRIES;

/** Index `czmName → rows`; a name with several overloads maps to several rows. */
export function catalogByName(catalog: readonly WgslPreludeEntry[] = PRELUDE_CATALOG): Map<string, WgslPreludeEntry[]> {
  const byName = new Map<string, WgslPreludeEntry[]>();
  for (const entry of catalog) {
    const rows = byName.get(entry.czmName);
    if (rows === undefined) byName.set(entry.czmName, [entry]);
    else rows.push(entry);
  }
  return byName;
}

/** The WGSL name of one overload; `null` when the name is not part of the terrain closure. */
export function wgslNameOf(czmName: string, overload: number | null = null, catalog: readonly WgslPreludeEntry[] = PRELUDE_CATALOG): string | null {
  const rows = catalog.filter((entry) => entry.czmName === czmName);
  if (rows.length === 0) return null;
  const exact = rows.find((entry) => entry.overload === overload);
  return (exact ?? rows[0])?.wgslName ?? null;
}

/**
 * The prelude declarations one set of `czm_` names needs.
 *
 * @throws when a name is not in the catalog: emitting a module that references an unknown `czm_`
 *   name would fail on the device with an unhelpful message, so the failure happens here instead.
 */
export function preludeFor(builtinNames: readonly string[], catalog: readonly WgslPreludeEntry[] = PRELUDE_CATALOG): readonly PreludeFragment[] {
  const byName = catalogByName(catalog);
  const fragments: PreludeFragment[] = [];
  const unknown: string[] = [];
  for (const name of [...new Set(builtinNames)].sort()) {
    const rows = byName.get(name);
    if (rows === undefined) {
      unknown.push(name);
      continue;
    }
    fragments.push({
      name,
      leafHash: "",
      wgsl: "",
      entries: rows,
    });
  }
  if (unknown.length > 0) {
    throw new Error(
      `wgsl-prelude: ${unknown.length} czm_ name(s) have no catalog entry: ${unknown.join(", ")}. ` +
        "Every czm_ built-in the terrain closure references MUST be catalogued (tasks.md T068); an unknown name is refused rather than silently dropped.",
    );
  }
  return fragments;
}

/**
 * Render the prelude text prepended to an emitted WGSL module.
 *
 * The text is the **whole** terrain prelude (`czm-prelude.wgsl`, inlined at build time), because the
 * emitter prunes unreachable declarations afterwards — passing only "the names the caller thinks are
 * needed" would be a second source of truth for reachability and could silently drop a
 * transitively-referenced helper. `fragments` therefore only has to be a non-empty subset of the
 * catalog for the render to be meaningful.
 */
export function renderPrelude(fragments: readonly PreludeFragment[], preludeText: string): string {
  if (fragments.length === 0) throw new Error("wgsl-prelude: renderPrelude() called with no fragments — an empty prelude would emit a module referencing undeclared czm_ helpers");
  const names = new Set(fragments.flatMap((fragment) => fragment.entries.map((entry) => entry.wgslName)));
  const missing = [...names].filter((name) => !name.startsWith("czm.") && !new RegExp(`\\b${name}\\b`).test(preludeText));
  if (missing.length > 0) throw new Error(`wgsl-prelude: the prelude text does not declare ${missing.join(", ")} — the catalog and czm-prelude.wgsl have drifted (run tools/scripts/gen-wgsl-catalog.mjs)`);
  return preludeText;
}

/** Every catalog row, grouped by kind — the shape the T068 unit suite asserts on. */
export function catalogSummary(catalog: readonly WgslPreludeEntry[] = PRELUDE_CATALOG): Record<string, number> {
  const summary: Record<string, number> = { constant: 0, function: 0, struct: 0, builtin: 0 };
  for (const entry of catalog) summary[entry.kind] = (summary[entry.kind] ?? 0) + 1;
  return summary;
}
